### PR TITLE
Add CategoryControlType "None" and VerticalPropertySpacing property

### LINKED ISSUE #277: PropertyGrid size
The PropertyGrid could be made smaller by removing surrounding adornment and reducing the space between Property Items.

### PR DESCRIPTION
**Pull request by dtwk1**
Hi 

Great project. Thought, though, the PropertyGrid control could be smaller.

So added an enum field, None, to CategoryControlType, in order to allow removal of the containing box surrounding the PropertyGrid

And a Dependency Property, VerticalPropertySpacing, to reduce to size of the spacing between the property grid items.

And updated the SimpleDemo to show effects of the change.

---
Fixes #277

### CODE REVIEW

**Comment by objorke** [comment]
Thanks! This looks good, except that the "SimpleDemo" has been changed so it is not so simple any more. Please revert those changes, and add the demonstration of the new options in the `Source\Examples\PropertyGrid\PropertyGridDemo` application instead. Then we can merge!

**Comment by objorke** [comment]
Please create an issue that we can reference in this PR and the change log.
Please update the change log and contributors files, too.

**Comment by dtwk1** [comment]
Reverted changes to SimpleDemo. Moved what was that code to PropertyGridDemo. 
Added an Issue. 
Updated the ChangeLog.
Updated the Contributors file.

**Comment by objorke** [comment]
Thanks for the contribution! I'll squash and merge this one.

**Pull request merged**
